server.port: 0
file:
  supplier:
    directory: C:\Users\WebUser\IdeaProjects
    filename-regex: .*\.(java|xml|md)
    excluded-directories: .git,.gradle,.idea,build,target,node_modules
spring:
  application.name: spring-ai-doc-loader
  ai.vectorstore.qdrant.initialize-schema: true
  cloud.function.definition: fileTreeSupplier|documentReader|splitter|vectorStoreWriter
#  cloud.function.definition: fileTreeSupplier|documentReader|splitter|scopeDeterminer|vectorStoreWriter

  ai:
    ollama:
#      base-url: http://localhost:11434
      embedding:
        model: bge-m3

logging:
  level:
    root: info
    org:
      springframework:
        ai:
          transformer:
            splitter: warn
