package ru.anblazhnov.springaidocloader;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

final class ProjectDiscovery implements AutoCloseable {
    private static final Logger log = LoggerFactory.getLogger(ProjectDiscovery.class);
    private static final Pattern GENERATED = Pattern.compile(
            "(?i)(?:^|/)(?:generated|generated-sources|generated-test-sources)(?:/|$)|@(?:[\\w.]+\\.)?Generated\\b|generated by|do not edit");
    private final DiscoveryProperties properties;
    private final List<DiscoveryProperties.Repository> repositories;
    private final Pattern filenames;
    private final Set<String> excludedDirectories;
    private final ProjectDocumentReaders readers;
    private final DiscoveryReport report;
    private int repositoryIndex;
    private DiscoveryProperties.Repository repository;
    private RepositoryRules rules;
    private MavenInventory inventory;
    private FileTreeWalker walker;

    ProjectDiscovery(DiscoveryProperties properties) throws IOException {
        properties.validate();
        this.properties = properties;
        repositories = repositories(properties);
        filenames = Pattern.compile(properties.getFilenameRegex());
        excludedDirectories = Arrays.stream(properties.getExcludedDirectories().split(","))
                .map(String::trim).filter(name -> !name.isEmpty()).collect(Collectors.toUnmodifiableSet());
        readers = new ProjectDocumentReaders(properties);
        report = new DiscoveryReport(properties.getReport());
    }

    DiscoveredFile next() {
        while (true) {
            if (walker == null && !openNextRepository()) return null;
            Path path = walker.next();
            if (path == null) {
                walker.close();
                walker = null;
                continue;
            }
            Map<String, Object> metadata = new LinkedHashMap<>(inventory.metadata(path));
            DiscoveredFile.FileKind kind = DiscoveredFile.FileKind.fromFilename(path);
            try {
                SourceText.Decoded decoded = SourceText.read(path, properties);
                if (SourceText.isXml(kind)) {
                    var root = XmlSupport.parse(decoded.text()).getDocumentElement();
                    kind = XmlSupport.classify(root, path);
                    metadata.put("namespace_uri", root.getNamespaceURI() == null ? "" : root.getNamespaceURI());
                    metadata.put("root_element", root.getLocalName());
                }
                boolean generated = GENERATED.matcher(metadata.get("relative_path") + "\n" + decoded.text()).find();
                metadata.put("generated", generated);
                metadata.put("file_kind", kind.name().toLowerCase(java.util.Locale.ROOT));
                metadata.put("language", kind.language);
                metadata.put("encoding", decoded.encoding());
                if (generated && properties.isExcludeGenerated()) {
                    report.record(metadata, kind.name(), "excluded", "generated_source");
                    continue;
                }
                if (kind == DiscoveredFile.FileKind.OTHER) {
                    report.record(metadata, kind.name(), "excluded", "unsupported_file_kind");
                    continue;
                }
                DiscoveredFile file = readers.prepare(new DiscoveredFile(path, kind, decoded.text(), metadata));
                report.record(file.metadata(), kind.name(), "included", generated ? "included_generated_source" : "supported_source");
                return file;
            }
            catch (Exception error) {
                if (error instanceof UncheckedIOException io) throw io;
                // Parser exception messages may contain credentials. Keep failure type/location only.
                failure(path, metadata, kind.name(), "read_or_parse_failed:" + error.getClass().getSimpleName());
            }
        }
    }

    private boolean openNextRepository() {
        if (repositoryIndex >= repositories.size()) return false;
        repository = repositories.get(repositoryIndex++);
        try {
            rules = new RepositoryRules(repository.root(), properties);
            inventory = new MavenInventory(repository, properties, rules);
            walker = new FileTreeWalker(repository.root(), this::include,
                    (path, error) -> failure(path, inventory.metadata(path), "unknown", "inaccessible:" + error.getClass().getSimpleName()));
            log.info("Discovering repository {} at {}", repository.id(), repository.root());
            return true;
        }
        catch (IOException error) { throw new UncheckedIOException(error); }
    }

    private boolean include(Path path, BasicFileAttributes attributes) {
        String reason = null;
        try {
            if (attributes.isSymbolicLink()) reason = "symbolic_link";
            else if (attributes.isDirectory() && excludedDirectories.contains(path.getFileName().toString())) reason = "configured_directory";
            else if (path.toAbsolutePath().normalize().equals(properties.getReport().toAbsolutePath().normalize())) reason = "discovery_report";
        else reason = rules.exclusion(path, attributes.isDirectory());
            if (reason == null && !attributes.isDirectory()) {
                if (!attributes.isRegularFile()) reason = "not_regular_file";
                else if (!filenames.matcher(path.getFileName().toString()).matches()) reason = "filename_filter";
                else if (attributes.size() > properties.getMaxFileSize()) reason = "file_too_large";
            }
        }
        catch (Exception error) {
            failure(path, inventory.metadata(path), "unknown", "ignore_rules_failed:" + error.getClass().getSimpleName());
            return false;
        }
        if (reason == null) return true;
        Map<String, Object> metadata = inventory.metadata(path);
        String kind = attributes.isDirectory() ? "directory" : DiscoveredFile.FileKind.fromFilename(path).name();
        report.record(metadata, kind, "excluded", reason);
        return false;
    }

    private void failure(Path path, Map<String, Object> metadata, String kind, String reason) {
        report.record(metadata, kind, "failed", reason);
        log.warn("Discovery failed for {}:{} ({})", repository.id(), RepositoryRules.portable(repository.root().relativize(path)), reason);
    }

    private static List<DiscoveryProperties.Repository> repositories(DiscoveryProperties properties) throws IOException {
        List<DiscoveryProperties.Repository> result = new ArrayList<>(properties.getRepositories());
        if (result.isEmpty()) {
            Path directory = properties.getDirectory().toAbsolutePath().normalize();
            requireDirectory(directory);
            if (Files.exists(directory.resolve(".git"), LinkOption.NOFOLLOW_LINKS)
                    || Files.isRegularFile(directory.resolve("pom.xml"), LinkOption.NOFOLLOW_LINKS)
                    || Files.isRegularFile(directory.resolve("build.gradle"), LinkOption.NOFOLLOW_LINKS)) {
                result.add(new DiscoveryProperties.Repository(directory.getFileName().toString(), directory));
            }
            else {
                try (var children = Files.list(directory)) {
                    children.filter(path -> Files.isDirectory(path, LinkOption.NOFOLLOW_LINKS))
                            .filter(path -> !Arrays.asList(properties.getExcludedDirectories().split(",")).contains(path.getFileName().toString()))
                            .sorted().forEach(path -> result.add(new DiscoveryProperties.Repository(path.getFileName().toString(), path)));
                }
                if (result.isEmpty()) result.add(new DiscoveryProperties.Repository(directory.getFileName().toString(), directory));
            }
        }
        Set<String> ids = new HashSet<>();
        List<DiscoveryProperties.Repository> normalized = new ArrayList<>();
        for (var configured : result) {
            if (configured.id() == null || configured.id().isBlank() || !ids.add(configured.id())) {
                throw new IllegalArgumentException("Each repository must have a nonblank, unique id");
            }
            if (configured.root() == null) throw new IllegalArgumentException("Repository root is required: " + configured.id());
            Path root = configured.root().toAbsolutePath().normalize();
            requireDirectory(root);
            if (normalized.stream().anyMatch(repo -> root.startsWith(repo.root()) || repo.root().startsWith(root))) {
                throw new IllegalArgumentException("Repository roots must not overlap: " + root);
            }
            normalized.add(new DiscoveryProperties.Repository(configured.id(), root));
        }
        return normalized;
    }

    private static void requireDirectory(Path root) {
        if (!Files.isDirectory(root, LinkOption.NOFOLLOW_LINKS)) {
            throw new IllegalArgumentException("Repository root must be an existing directory, not a symlink: " + root);
        }
    }

    @Override public void close() {
        if (walker != null) walker.close();
        try { report.close(); }
        catch (IOException error) { throw new UncheckedIOException(error); }
    }
}
